name = "promptcraft-backend"
main = "server.js"
compatibility_date = "2025-08-19"

[vars]
MODEL_PROVIDER = "cloudflare"
OPENAI_API_KEY = "your-openai-key-here"
OPENAI_MODEL = "gpt-4o-mini"
HF_API_URL = ""
HF_API_KEY = ""
CLOUDFLARE_ACCOUNT_ID="9e20a2d23e8227768214ace8238988ed"
CLOUDFLARE_API_TOKEN="3pY21gPkOtB2nE_kB52QIKiSiM0910yy1b9A5N8d"
CLOUDFLARE_MODEL="@cf/meta/llama-3-8b-instruct"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false




